In [1]:
import tensorflow as tf


c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is depr

In [2]:
tf.__version__
import tensorflow_datasets as tfds

'1.14.0'

In [ ]:
tfds.list_builders()

In [ ]:
(train_data,validation_data,test_data)=tfds.load(name='imdb_reviews',split=('train[:60%]','train[60%:]','test'),as_supervised=True)

In [5]:
train_examples_batch,train_labels_batch=next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: id=200, shape=(10,), dtype=string, numpy=
array([b'This is a big step down after the surprisingly enjoyable original. This sequel isn\'t nearly as fun as part one, and it instead spends too much time on plot development. Tim Thomerson is still the best thing about this series, but his wisecracking is toned down in this entry. The performances are all adequate, but this time the script lets us down. The action is merely routine and the plot is only mildly interesting, so I need lots of silly laughs in order to stay entertained during a "Trancers" movie. Unfortunately, the laughs are few and far between, and so, this film is watchable at best.',
       b"Perhaps because I was so young, innocent and BRAINWASHED when I saw it, this movie was the cause of many sleepless nights for me. I haven't seen it since I was in seventh grade at a Presbyterian school, so I am not sure what effect it would have on me now. However, I will say that it left an impression on me... and most of my

In [6]:
train_labels_batch

<tf.Tensor: id=201, shape=(10,), dtype=int64, numpy=array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0], dtype=int64)>

In [7]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(pretrained_model, input_shape=[], dtype=tf.string, trainable=True)

In [8]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: id=381, shape=(2, 20), dtype=float32, numpy=
array([[ 2.209591  , -2.7093675 ,  3.6802928 , -1.0291991 , -4.1671185 ,
        -2.4566064 , -2.2519937 , -0.36589956,  1.9485804 , -3.1104462 ,
        -2.4610963 ,  1.3139242 , -0.9161584 , -0.16625322, -3.723651  ,
         1.8498232 ,  3.499562  , -1.2373022 , -2.8403084 , -1.213074  ],
       [ 1.9055302 , -4.11395   ,  3.6038654 ,  0.28555924, -4.658998  ,
        -5.5433393 , -3.2735848 ,  1.9235417 ,  3.8461034 ,  1.5882455 ,
        -2.64167   ,  0.76057523, -0.14820506,  0.9115291 , -6.45758   ,
         2.3990374 ,  5.0985413 , -3.2776263 , -3.2652326 , -1.2345369 ]],
      dtype=float32)>

In [9]:
train_examples_batch[:2]

<tf.Tensor: id=385, shape=(2,), dtype=string, numpy=
array([b'This is a big step down after the surprisingly enjoyable original. This sequel isn\'t nearly as fun as part one, and it instead spends too much time on plot development. Tim Thomerson is still the best thing about this series, but his wisecracking is toned down in this entry. The performances are all adequate, but this time the script lets us down. The action is merely routine and the plot is only mildly interesting, so I need lots of silly laughs in order to stay entertained during a "Trancers" movie. Unfortunately, the laughs are few and far between, and so, this film is watchable at best.',
       b"Perhaps because I was so young, innocent and BRAINWASHED when I saw it, this movie was the cause of many sleepless nights for me. I haven't seen it since I was in seventh grade at a Presbyterian school, so I am not sure what effect it would have on me now. However, I will say that it left an impression on me... and most of my 

In [10]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_data.shuffle(10000).batch(512),
         epochs=30,
         validation_data=validation_data.batch(512),
         verbose=1)

Epoch 1/30
30/30 [==============================] - 8s 267ms/step - loss: 0.8437 - accuracy: 0.5423 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/30
30/30 [==============================] - 4s 147ms/step - loss: 0.6492 - accuracy: 0.6367 - val_loss: 0.6022 - val_accuracy: 0.6743
Epoch 3/30
30/30 [==============================] - 4s 137ms/step - loss: 0.5879 - accuracy: 0.6963 - val_loss: 0.5585 - val_accuracy: 0.7216
Epoch 4/30
30/30 [==============================] - 5s 181ms/step - loss: 0.5504 - accuracy: 0.7330 - val_loss: 0.5302 - val_accuracy: 0.7485
Epoch 5/30
30/30 [==============================] - 4s 148ms/step - loss: 0.5148 - accuracy: 0.7579 - val_loss: 0.5038 - val_accuracy: 0.7658
Epoch 6/30
30/30 [==============================] - 5s 178ms/step - loss: 0.4865 - accuracy: 0.7787 - val_loss: 0.4787 - val_accuracy: 0.7853
Epoch 7/30
30/30 [==============================] - 4s 149ms/step - loss: 0.4564 - accuracy: 0.7987 - val_loss: 0.4537 - val_accuracy: 0.801

In [13]:
model.predict(["This is the worst movie I have ever seen"])

array([[0.11566346]], dtype=float32)

In [14]:
model.predict(["An excellent movie that I enjoyed a lot"])

array([[0.99994004]], dtype=float32)

In [15]:
model.predict(["how can one make such a horrible movie? there is no story, acting direction everything is very poor"])

array([[0.03086592]], dtype=float32)

In [16]:
def predict_review(review):
    return round(model.predict([review])[0][0]*10,2)

In [17]:
predict_review("An excellent movie that I enjoyed a lot")

10.0

In [20]:
predict_review("excellent")

10.0

In [21]:
predict_review("This is the worst movie I have ever seen")

1.16

In [1]:
import pickle
with open('movie_review.pickle','wb') as f:
    pickle.dump(model,f)

NameError: name 'model' is not defined

In [ ]:
==